export interface QuizQuestion {
  type: 'grammar' | 'fill' | 'vocabulary' | 'idiom';
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export interface Idiom {
  phrase: string;
  meaning: string;
  origin: string;
  dialogue: string[];
}

export const getTodayKey = (): string => {
  return new Date().toISOString().split('T')[0];
};

export const getDayIndex = (arrayLength: number): number => {
  const now = new Date();
  const dayOfYear = Math.floor((now.getTime() - new Date(now.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
  return dayOfYear % arrayLength;
};

// Seeding 10 questions per day
export const getDailyQuizQuestions = (): QuizQuestion[] => {
  const dayIndex = getDayIndex(100);
  const questions: QuizQuestion[] = [];
  for (let i = 0; i < 10; i++) {
    const qIndex = (dayIndex * 7 + i * 13) % QUIZ_BANK.length;
    questions.push(QUIZ_BANK[qIndex]);
  }
  return questions;
};

export const IDIOMS: Idiom[] = [
  { phrase: 'Hit the ground running', meaning: 'To start something and immediately work at full speed and efficiency.', origin: 'Likely military: soldiers jumping from vehicles and running immediately without losing momentum.', dialogue: ['A: How did your first week at the new job go?', 'B: Really well! I hit the ground running — I already closed two deals.'] },
  { phrase: 'Bite off more than you can chew', meaning: 'To take on more responsibility or work than you can handle.', origin: 'From eating: literally biting a piece too large to chew properly. Recorded in use since the 1800s.', dialogue: ['A: You\'re running the marathon AND doing the triathlon the same weekend?', 'B: I know — I definitely bit off more than I can chew this time.'] },
  { phrase: 'The elephant in the room', meaning: 'An obvious problem or difficult situation that no one wants to discuss.', origin: 'The phrase became popular in the 20th century to describe something so obvious it\'s hard to ignore.', dialogue: ['A: Nobody has mentioned the budget cuts in this meeting.', 'B: I know. The elephant in the room is that three departments will be cut.'] },
  { phrase: 'A penny for your thoughts', meaning: 'Used to ask someone what they are thinking, especially if they seem lost in thought.', origin: 'First used in writing by Sir Thomas More in 1522 — even then, a "penny\'s worth" of thought.', dialogue: ['A: You\'ve been staring at the window for ages.', 'B: Oh — sorry! A penny for your thoughts? I was just worried about tomorrow.'] },
  { phrase: 'Kill two birds with one stone', meaning: 'To achieve two goals with one action.', origin: 'Ancient proverb. The first recorded English version appears around the 17th century.', dialogue: ['A: I need to go to the post office and buy groceries.', 'B: The new store near the post office has both — kill two birds with one stone!'] },
  { phrase: 'Under the gun', meaning: 'Under pressure to meet a deadline or complete something urgently.', origin: 'Military origin — originally "under fire." Evolved to mean being pressured by deadlines.', dialogue: ['A: Can you help me with this report?', 'B: I\'m really under the gun right now — the presentation is in an hour.'] },
  { phrase: 'Throw in the towel', meaning: 'To admit defeat; to give up on something.', origin: 'Boxing: a trainer throws a towel into the ring to stop the fight and concede defeat for their boxer.', dialogue: ['A: Are you still trying to learn guitar?', 'B: Not really. After six months with no progress, I kind of threw in the towel.'] },
  { phrase: 'Out of the blue', meaning: 'Unexpectedly; without warning or prior notice.', origin: 'From "a bolt out of the blue" — lightning striking from a clear blue sky, completely unexpected.', dialogue: ['A: Did you hear from your old manager?', 'B: Yes! He called me out of the blue and offered me a job!'] },
  { phrase: 'On the fence', meaning: 'Undecided or neutral about something.', origin: 'Literal image of someone sitting on a fence between two properties, choosing neither side.', dialogue: ['A: Are you coming to the party on Saturday?', 'B: I\'m still on the fence. It depends on how work goes this week.'] },
  { phrase: 'Beat around the bush', meaning: 'To avoid talking about the main point; to speak vaguely.', origin: 'From bird hunting: beaters would hit bushes to flush birds out — working around rather than directly.', dialogue: ['A: Can you just tell me the price?', 'B: Sorry, I\'ll stop beating around the bush — it\'s $500.'] },
  { phrase: 'Burn bridges', meaning: 'To permanently damage a relationship or opportunity.', origin: 'Military strategy: burning a bridge behind you prevents enemy pursuit but also your own retreat.', dialogue: ['A: I want to quit by just walking out tomorrow.', 'B: Don\'t burn bridges — give proper notice and leave professionally.'] },
  { phrase: 'The ball is in your court', meaning: 'It is now your responsibility to take the next action or make the next decision.', origin: 'From tennis: when the ball lands on your side, it\'s your turn to respond.', dialogue: ['A: I\'ve sent her my proposal. Now what?', 'B: Now the ball is in her court — just wait for her response.'] },
  { phrase: 'Cut corners', meaning: 'To do something the easy or cheaper way, often sacrificing quality.', origin: 'Carpenters and architects historically cut corners of land lots or buildings to save material.', dialogue: ['A: Why did the renovation only take two weeks?', 'B: They cut corners. The tiles are already cracking.'] },
  { phrase: 'Go back to the drawing board', meaning: 'To start a project over completely; to begin from scratch.', origin: 'Refers to an architect\'s or engineer\'s drawing board — starting a design from the beginning.', dialogue: ['A: The client rejected our entire proposal.', 'B: Back to the drawing board. Let\'s meet Monday morning.'] },
  { phrase: 'Read between the lines', meaning: 'To understand something that is not explicitly stated; to find hidden meaning.', origin: 'Refers to reading invisible/hidden messages between the written lines using invisible ink.', dialogue: ['A: Did she say she was upset?', 'B: Not directly, but if you read between the lines, she definitely is.'] },
  { phrase: 'Put your foot in your mouth', meaning: 'To say something embarrassing or inappropriate by accident.', origin: 'American English: the image of accidentally putting your own foot in your mouth, a clumsy act.', dialogue: ['A: I asked her when the baby was due and she\'s not pregnant!', 'B: Oh no. You really put your foot in your mouth there.'] },
  { phrase: 'Bite the bullet', meaning: 'To endure a painful or difficult situation with courage.', origin: 'Pre-anesthesia surgery: patients would bite on a bullet to endure the pain of the operation.', dialogue: ['A: I don\'t want to call and apologize.', 'B: I know it\'s hard, but just bite the bullet and do it. You\'ll feel better.'] },
  { phrase: 'Barking up the wrong tree', meaning: 'To pursue a mistaken or misguided course of action; to have the wrong idea.', origin: 'Hunting dogs would sometimes bark at a tree after an animal had moved to another tree.', dialogue: ['A: I think John took my pen.', 'B: You\'re barking up the wrong tree — I saw Sarah borrow it earlier.'] },
  { phrase: 'When pigs fly', meaning: 'Something that will never happen.', origin: 'Pigs cannot fly — the phrase describes an impossible condition. Used sarcastically.', dialogue: ['A: Do you think they\'ll ever lower prices?', 'B: When pigs fly. This company never gives discounts.'] },
  { phrase: 'Bite the hand that feeds you', meaning: 'To act against those who are helping or supporting you.', origin: 'The image of a dog biting the hand of the owner who feeds it — blatant ingratitude.', dialogue: ['A: He complained about the company publicly while still working there.', 'B: That\'s biting the hand that feeds you. Very risky.'] }
];

export const QUIZ_BANK: QuizQuestion[] = [
  { type: 'grammar', question: 'Which sentence uses the correct form of the verb?', options: ['She don\'t like coffee.', 'She doesn\'t like coffee.', 'She isn\'t like coffee.', 'She don\'t likes coffee.'], correct: 1, explanation: '"Doesn\'t" is correct for third-person singular (she/he/it) in present simple.' },
  { type: 'grammar', question: 'Choose the correct sentence:', options: ['I am agree with you.', 'I am agreeing with you.', 'I agree with you.', 'I am agreed with you.'], correct: 2, explanation: '"Agree" is a stative verb and doesn\'t use the -ing form in this context.' },
  { type: 'grammar', question: 'Which is grammatically correct?', options: ['Neither the students nor the teacher were ready.', 'Neither the students nor the teacher was ready.', 'Neither the students nor the teacher is ready.', 'Neither the students nor the teacher are ready.'], correct: 1, explanation: 'With "neither...nor," the verb agrees with the noun closest to it — "teacher" (singular).' },
  { type: 'grammar', question: 'Which sentence is correct?', options: ['I have been to Paris last year.', 'I went to Paris last year.', 'I have gone to Paris last year.', 'I did go to Paris last year.'], correct: 1, explanation: 'Use past simple ("went") with specific past time expressions like "last year."' },
  { type: 'grammar', question: 'Choose the correct option: "If I _____ rich, I would travel the world."', options: ['am', 'was', 'were', 'be'], correct: 2, explanation: 'In second conditional sentences (hypothetical situations), use "were" for all subjects.' },
  { type: 'grammar', question: 'Which is correct: "There _____ a lot of people at the event."', options: ['was', 'were', 'is', 'are'], correct: 1, explanation: '"People" is a plural noun, so use "were" in past tense.' },
  { type: 'grammar', question: 'Select the correct sentence:', options: ['She works hardly to succeed.', 'She works hard to succeed.', 'She hardly works to succeed.', 'She hard works to succeed.'], correct: 1, explanation: '"Hard" is both an adjective and an adverb. "Hardly" means "barely" — completely different meaning!' },
  { type: 'grammar', question: 'Which uses articles correctly?', options: ['She plays the piano every evening.', 'She plays a piano every evening.', 'She plays piano every evening.', 'She plays an piano every evening.'], correct: 0, explanation: 'Use "the" with musical instruments when talking about the skill or activity.' },
  { type: 'grammar', question: 'Choose the correct preposition: "I\'m good _____ cooking."', options: ['in', 'at', 'with', 'for'], correct: 1, explanation: '"Good at" + skill/activity is the standard preposition combination.' },
  { type: 'grammar', question: 'Which sentence is in the passive voice?', options: ['The chef prepared the meal.', 'The meal was prepared by the chef.', 'The chef is preparing the meal.', 'The chef had prepared the meal.'], correct: 1, explanation: 'Passive voice: object + "to be" + past participle + (by + agent). "Was prepared" is passive.' },
  { type: 'grammar', question: 'Which modal expresses strong certainty about the present?', options: ['might', 'could', 'must', 'should'], correct: 2, explanation: '"Must" expresses strong certainty or logical deduction. "He must be tired" = I\'m very certain he is.' },
  { type: 'grammar', question: 'Choose the correct form: "By next year, I _____ here for a decade."', options: ['will live', 'will have been living', 'will have lived', 'will be living'], correct: 2, explanation: 'Future perfect "will have lived" shows completion by a future point: "by next year."' },
  { type: 'grammar', question: 'Which is a dangling modifier?', options: ['Walking to school, the rain started.', 'While I was walking to school, the rain started.', 'As I walked to school, the rain started.', 'The rain started while I walked to school.'], correct: 0, explanation: '"Walking to school" dangles because the rain can\'t walk. The subject must match the modifier.' },
  { type: 'grammar', question: 'Select the correct comparative form:', options: ['This is more easier than I thought.', 'This is more easy than I thought.', 'This is easier than I thought.', 'This is easyer than I thought.'], correct: 2, explanation: 'Don\'t use "more" + "-er" together. Short adjectives use -er: "easier."' },
  { type: 'grammar', question: 'Which sentence shows correct subject-verb agreement?', options: ['The news are shocking.', 'The news is shocking.', 'The news have been shocking.', 'The news be shocking.'], correct: 1, explanation: '"News" is an uncountable noun that takes a singular verb.' },

  // Fill in the blank
  { type: 'fill', question: 'Complete the idiom: "It\'s raining _____ and dogs."', options: ['mice', 'cats', 'pigs', 'birds'], correct: 1, explanation: '"Raining cats and dogs" means raining very heavily. Origin possibly from 17th century England.' },
  { type: 'fill', question: 'Fill in: "She arrived _____ the right time."', options: ['in', 'on', 'at', 'by'], correct: 2, explanation: '"Arrive at the right time" — use "at" for specific times and points.' },
  { type: 'fill', question: '"Despite working all night, he felt _____." (Choose the best word)', options: ['tired', 'energized', 'sleepy', 'weak'], correct: 1, explanation: '"Despite" signals a contrast, so the surprising/opposite result: he felt energized.' },
  { type: 'fill', question: 'Fill in: "I\'m looking forward _____ meeting you."', options: ['to', 'for', 'at', 'of'], correct: 0, explanation: '"Look forward to" is a fixed phrase. "To" is a preposition here, so use the -ing form after it.' },
  { type: 'fill', question: '"She spoke so quietly that I could _____ hear her."', options: ['nearly', 'barely', 'almost', 'mostly'], correct: 1, explanation: '"Barely" (= almost not at all) is the most natural fit here for difficulty hearing.' },
  { type: 'fill', question: 'Fill in: "He has been studying English _____ three years."', options: ['since', 'for', 'during', 'from'], correct: 1, explanation: '"For" + duration (three years). "Since" + starting point (since 2021).' },
  { type: 'fill', question: '"I\'d rather you _____ here." (Choose the correct form)', options: ['stayed', 'stay', 'to stay', 'staying'], correct: 0, explanation: '"I\'d rather + subject + past tense" is the correct structure for this expression.' },
  { type: 'fill', question: 'Complete: "By the time I arrived, the meeting _____ already started."', options: ['has', 'had', 'was', 'did'], correct: 1, explanation: 'Past perfect "had started" shows an action completed before another past action.' },
  { type: 'fill', question: '"The more you practice, _____ you improve."', options: ['the most', 'the more', 'the better', 'much more'], correct: 2, explanation: '"The more...the better" is the correct parallel comparative structure.' },
  { type: 'fill', question: '"She _____ used to eating spicy food." (current state)', options: ['is', 'gets', 'was', 'has'], correct: 0, explanation: '"Be used to" (present state) = accustomed to. Different from "used to" (past habit).' },
  { type: 'fill', question: 'Fill in: "We need to _____ a decision before tomorrow."', options: ['do', 'take', 'make', 'have'], correct: 2, explanation: '"Make a decision" is the correct collocations. You "make" decisions, not "do" them.' },
  { type: 'fill', question: '"He apologized _____ being rude."', options: ['for', 'of', 'to', 'about'], correct: 0, explanation: '"Apologize for" + noun/gerund is the standard collocation.' },
  { type: 'fill', question: 'Choose the best word: "The evidence was _____; we couldn\'t ignore it."', options: ['vague', 'compelling', 'unreliable', 'absent'], correct: 1, explanation: '"Compelling" = so strong it demands attention. Context says they couldn\'t ignore it.' },
  { type: 'fill', question: '"I\'m not _____ to the idea — let\'s talk about it."', options: ['open', 'opposed', 'closed', 'resistant'], correct: 0, explanation: '"Open to an idea" = willing to consider it. A common conversational phrase.' },
  { type: 'fill', question: '"She _____ the exam with flying colors."', options: ['passed', 'took', 'cleared', 'finished'], correct: 0, explanation: '"Pass with flying colors" means to succeed excellently. "Passed" is the correct verb.' },

  // Vocabulary MCQ
  { type: 'vocabulary', question: 'What does "verbose" mean?', options: ['Very quiet and reserved', 'Using too many words', 'Being very angry', 'Lacking confidence'], correct: 1, explanation: '"Verbose" means using more words than necessary. From Latin "verbum" = word.' },
  { type: 'vocabulary', question: 'What does "ambivalent" mean?', options: ['Clearly decided', 'Having mixed or contradictory feelings', 'Very enthusiastic', 'Completely uninterested'], correct: 1, explanation: '"Ambivalent" = having two conflicting feelings. "Ambi" = both, "valent" = strong.' },
  { type: 'vocabulary', question: 'What is a "proponent"?', options: ['Someone who opposes something', 'A person who advocates for something', 'An impartial observer', 'A financial supporter only'], correct: 1, explanation: 'A "proponent" is a person who supports or advocates for a cause or proposal.' },
  { type: 'vocabulary', question: 'What does "aloof" mean?', options: ['Very friendly and outgoing', 'Cool and distant', 'Highly intelligent', 'Extremely busy'], correct: 1, explanation: '"Aloof" means not friendly or forthcoming; keeping at a distance emotionally or physically.' },
  { type: 'vocabulary', question: 'What does "candid" mean?', options: ['Secretive and guarded', 'Truthful and straightforward', 'Overly flattering', 'Diplomatically vague'], correct: 1, explanation: '"Candid" = honest and direct. "Candid camera" catches people being natural and genuine.' },
  { type: 'vocabulary', question: 'What is "eloquence"?', options: ['Speaking in a foreign language', 'Fluent and persuasive speaking or writing', 'Using technical jargon', 'Speaking very quietly'], correct: 1, explanation: '"Eloquence" is the ability to express ideas fluently, clearly, and persuasively.' },
  { type: 'vocabulary', question: 'What does "pragmatic" mean?', options: ['Dealing with dreams and ideals', 'Focused on practical matters', 'Overly emotional', 'Theoretically oriented'], correct: 1, explanation: '"Pragmatic" = practical, realistic, focused on what works rather than what\'s ideal.' },
  { type: 'vocabulary', question: 'Which word means "to make something worse"?', options: ['Alleviate', 'Mitigate', 'Exacerbate', 'Ameliorate'], correct: 2, explanation: '"Exacerbate" = to make a bad situation worse. The others mean to improve or lessen.' },
  { type: 'vocabulary', question: 'What does "meticulous" mean?', options: ['Careless and hasty', 'Showing extreme care with details', 'Extremely generous', 'Bold and adventurous'], correct: 1, explanation: '"Meticulous" = very careful and precise, paying attention to every small detail.' },
  { type: 'vocabulary', question: 'What does "tenacious" mean?', options: ['Easily giving up', 'Holding firm; persistent', 'Agreeable and flexible', 'Rapid and efficient'], correct: 1, explanation: '"Tenacious" = holding on tightly; refusing to give up. From Latin "tenere" = to hold.' },
  { type: 'vocabulary', question: 'What is an "anecdote"?', options: ['A type of medication', 'A short personal story', 'An official report', 'A scientific theory'], correct: 1, explanation: 'An "anecdote" is a short, amusing or interesting story about a real incident or person.' },
  { type: 'vocabulary', question: 'What does "sarcastic" mean?', options: ['Genuinely complimentary', 'Saying the opposite of what you mean to mock', 'Speaking very formally', 'Being overly polite'], correct: 1, explanation: 'Sarcasm involves saying the opposite of what you mean, often to criticize or mock humorously.' },
  { type: 'vocabulary', question: 'What does "novice" mean?', options: ['An expert in a field', 'A person new to a skill', 'An ancient tradition', 'A formal agreement'], correct: 1, explanation: 'A "novice" is a beginner or someone new to a subject or activity.' },
  { type: 'vocabulary', question: 'What does "concise" mean?', options: ['Very long and detailed', 'Brief and to the point', 'Extremely complex', 'Emotionally expressive'], correct: 1, explanation: '"Concise" = expressing much in few words. Opposite of verbose or wordy.' },
  { type: 'vocabulary', question: 'What does "collaborate" mean?', options: ['To compete fiercely', 'To work jointly on something', 'To criticize another\'s work', 'To copy someone\'s idea'], correct: 1, explanation: '"Collaborate" = work together with others. From Latin "co" (together) + "laborare" (to work).' },

  // Idiom meaning
  { type: 'idiom', question: 'What does "bite the bullet" mean?', options: ['To eat something hard', 'To endure a painful situation bravely', 'To make a rash decision', 'To argue aggressively'], correct: 1, explanation: 'From battlefields where patients bit bullets during surgery. Means to endure difficulty.' },
  { type: 'idiom', question: 'What does "hit the nail on the head" mean?', options: ['To be aggressive', 'To describe exactly what is right', 'To cause an accident', 'To complete a project'], correct: 1, explanation: 'Like hitting a nail perfectly — you\'ve identified the exact truth or made a perfect point.' },
  { type: 'idiom', question: 'What does "break the ice" mean?', options: ['To make something cold', 'To do something to relieve tension in a social situation', 'To destroy a valuable object', 'To start an argument'], correct: 1, explanation: 'Like breaking ice on a ship\'s path. "Breaking the ice" makes social interaction easier.' },
  { type: 'idiom', question: 'What does "burning the midnight oil" mean?', options: ['Being careless with resources', 'Working very late into the night', 'Starting a fire', 'Wasting energy'], correct: 1, explanation: 'Before electricity, people burned oil lamps when working late. Now means working into the night.' },
  { type: 'idiom', question: 'What does "let the cat out of the bag" mean?', options: ['To release an animal', 'To reveal a secret accidentally', 'To make a mess', 'To be generous'], correct: 1, explanation: 'Originates from market scams where a cheap pig was secretly replaced with a cat in a bag.' },
  { type: 'idiom', question: 'What does "once in a blue moon" mean?', options: ['During nighttime only', 'Very rarely', 'Every month', 'Always and consistently'], correct: 1, explanation: 'A "blue moon" is a rare second full moon in a month, hence very rarely.' },
  { type: 'idiom', question: 'What does "cost an arm and a leg" mean?', options: ['To involve physical injury', 'To be very expensive', 'To require physical effort', 'To be completely free'], correct: 1, explanation: '"Cost an arm and a leg" = extremely expensive. Implies giving up body parts for the price.' },
  { type: 'idiom', question: 'What does "under the weather" mean?', options: ['To be caught in rain', 'To feel slightly ill', 'To be outdoors', 'To feel anxious'], correct: 1, explanation: '"Under the weather" = not feeling well. Nautical origin — sick sailors went below deck (under the weather).' },
  { type: 'idiom', question: 'What does "add fuel to the fire" mean?', options: ['To be helpful', 'To make a bad situation worse', 'To start a new conversation', 'To bring warmth'], correct: 1, explanation: 'Like adding fuel to a fire makes it bigger — making an already bad situation worse.' },
  { type: 'idiom', question: 'What does "a blessing in disguise" mean?', options: ['A hypocritical person', 'Something good that at first seemed bad', 'An unexpected visitor', 'A hidden cost'], correct: 1, explanation: 'Something that seems bad but turns out to be good — a blessing hidden as something bad.' },
  { type: 'idiom', question: 'What does "spill the beans" mean?', options: ['To make a mess while cooking', 'To reveal secret information', 'To be overly generous', 'To start a rumor'], correct: 1, explanation: '"Spill the beans" = to reveal secret information, often by accident.' },
  { type: 'idiom', question: 'What does "get a taste of your own medicine" mean?', options: ['To try a new food', 'To experience the same negative treatment you give others', 'To recover from illness', 'To learn from mistakes'], correct: 1, explanation: 'When someone who does harm to others experiences that same harm themselves.' },
  { type: 'idiom', question: 'What does "sit on the fence" mean?', options: ['To avoid making a decision', 'To watch an event from outside', 'To wait for someone', 'To remain physically still'], correct: 0, explanation: '"Sit on the fence" = to avoid taking a side or making a decision on an issue.' },
  { type: 'idiom', question: 'What does "the ball is in your court" mean?', options: ['It\'s time to play a sport', 'It\'s your turn to take action or decide', 'Someone else is responsible now', 'You have an advantage in sport'], correct: 1, explanation: 'From tennis — when the ball is on your side, it\'s YOUR responsibility to return it (act).' },
  { type: 'idiom', question: 'What does "kick the bucket" mean?', options: ['To start something new', 'To die', 'To make a mistake', 'To refuse to cooperate'], correct: 1, explanation: '"Kick the bucket" is an informal/humorous way of saying someone has died.' },

  // Additional questions to reach 200+
  { type: 'grammar', question: 'Which sentence uses the present perfect correctly?', options: ['I have seen that movie yesterday.', 'I saw that movie since Monday.', 'I\'ve already seen that movie.', 'I have saw that movie before.'], correct: 2, explanation: 'Present perfect uses "have/has + past participle." Avoid using it with specific past time words like "yesterday."' },
  { type: 'vocabulary', question: 'What does "inevitable" mean?', options: ['Impossible to prevent', 'Easy to avoid', 'Very unlikely', 'Extremely surprising'], correct: 0, explanation: '"Inevitable" = certain to happen; impossible to avoid. "In" (not) + "evitable" (avoidable).' },
  { type: 'fill', question: '"You should _____ a professional about this legal issue."', options: ['refer', 'consult', 'speak', 'call'], correct: 1, explanation: '"Consult a professional" = seek expert advice. The standard collocation in formal contexts.' }
];

export interface Word {
  word: string;
  pos: string;
  def: string;
  example: string;
  tip: string;
}

export const WORDS: Word[] = [
  { word: 'Serendipity', pos: 'noun', def: 'The occurrence and development of events by chance in a happy or beneficial way.', example: 'Finding that perfect café was pure serendipity.', tip: 'Think "serene + happy dip" — a dip into a serene, happy moment.' },
  { word: 'Ephemeral', pos: 'adjective', def: 'Lasting for a very short time; transitory.', example: 'The beauty of cherry blossoms is ephemeral, lasting only a week.', tip: 'Sounds like "a femoral" — femoral arteries briefly pulse with life.' },
  { word: 'Ubiquitous', pos: 'adjective', def: 'Present, appearing, or found everywhere.', example: 'Smartphones have become ubiquitous in modern life.', tip: 'U-BIQ-uitous — "U-B-I" — you be *everywhere*.' },
  { word: 'Loquacious', pos: 'adjective', def: 'Tending to talk a great deal; talkative.', example: 'Our loquacious guide kept everyone entertained throughout the tour.', tip: 'LOQU = speak (Latin). Loquacious = loves to speak.' },
  { word: 'Perspicacious', pos: 'adjective', def: 'Having a ready insight; shrewd.', example: 'Her perspicacious observations helped the team avoid a costly mistake.', tip: '"Perspicacious" — per-SPIC-acious, you can SPY the truth clearly.' },
  { word: 'Melancholy', pos: 'noun/adj', def: 'A feeling of pensive sadness, typically with no obvious cause.', example: 'A sense of melancholy settled over him as autumn arrived.', tip: 'Mel = honey (Greek), chol = bile. Ancient Greeks thought black bile caused sadness.' },
  { word: 'Eloquent', pos: 'adjective', def: 'Fluent or persuasive in speaking or writing.', example: 'Her eloquent speech moved the entire audience to tears.', tip: 'ELOQ = speak out. Eloquent people speak beautifully.' },
  { word: 'Resilient', pos: 'adjective', def: 'Able to withstand or recover quickly from difficult conditions.', example: 'Children are remarkably resilient and often bounce back from setbacks quickly.', tip: 'Resilient = re-SILI-ent. Silica (rubber) bounces back — so do resilient people.' },
  { word: 'Ambiguous', pos: 'adjective', def: 'Open to more than one interpretation; not having one obvious meaning.', example: 'The contract contained several ambiguous clauses that led to a dispute.', tip: '"Ambi" = both. Ambiguous things point in TWO directions.' },
  { word: 'Candid', pos: 'adjective', def: 'Truthful and straightforward; frank.', example: 'I appreciate your candid feedback — it helps me improve.', tip: 'Candid = CAN-did. You CAN say what you DID honestly.' },
  { word: 'Diligent', pos: 'adjective', def: 'Having or showing care and conscientiousness in one\'s work or duties.', example: 'She was diligent in her studies and always completed assignments on time.', tip: 'Dili-GENT. A diligent person is a true GENT(leman) of work.' },
  { word: 'Empathy', pos: 'noun', def: 'The ability to understand and share the feelings of another.', example: 'Good leaders show empathy toward the challenges their team faces.', tip: '"Em" = into, "pathos" = feeling. You step INTO someone\'s feelings.' },
  { word: 'Frugal', pos: 'adjective', def: 'Sparing or economical with money or food; not wasteful.', example: 'Living a frugal lifestyle allowed her to retire early.', tip: 'FRU-gal. Frugal people are FRUGAL with every FRU(it) they buy.' },
  { word: 'Gregarious', pos: 'adjective', def: 'Fond of company; sociable.', example: 'He\'s naturally gregarious and makes friends wherever he goes.', tip: 'GREGAR = flock (Latin). Gregarious people love being in a FLOCK.' },
  { word: 'Haughty', pos: 'adjective', def: 'Arrogantly superior and disdainful.', example: 'Her haughty attitude alienated potential allies.', tip: 'HAUGHTY = HIGH-ty. Haughty people think they\'re HIGH above others.' },
  { word: 'Impetuous', pos: 'adjective', def: 'Acting or done quickly and without thought or care.', example: 'His impetuous decision to quit led to months of regret.', tip: 'IM-pet-uous. Like an impatient PET that rushes forward recklessly.' },
  { word: 'Jovial', pos: 'adjective', def: 'Cheerful and friendly.', example: 'The jovial host made every guest feel welcome and relaxed.', tip: 'JOVIAL = JOVE. Jove (Jupiter) was the cheerful, festive god.' },
  { word: 'Kinetic', pos: 'adjective', def: 'Relating to or resulting from motion.', example: 'The kinetic energy of the waterfall powers the entire village.', tip: 'KINE = motion (Greek). Kinetic things are always MOVING.' },
  { word: 'Languid', pos: 'adjective', def: 'Displaying or having a disinclination for physical exertion or effort.', example: 'He spent a languid afternoon reading on the hammock.', tip: 'LANG-uid. LONG, slow, lazy — just like a languid day.' },
  { word: 'Magnanimous', pos: 'adjective', def: 'Generous or forgiving, especially toward a rival or someone less powerful.', example: 'In victory, she was magnanimous, congratulating her opponent warmly.', tip: 'MAGNA = great, ANIMUS = spirit. A magnanimous person has a GREAT spirit.' },
  { word: 'Nonchalant', pos: 'adjective', def: 'Feeling or appearing casually calm and relaxed; not displaying anxiety.', example: 'He was nonchalant about the interview, as if he already had the job.', tip: 'Non-chalant = NOT-warm (French). Acting cool, not heated up about anything.' },
  { word: 'Ostracize', pos: 'verb', def: 'Exclude from a society or group.', example: 'The new student feared being ostracized for her different accent.', tip: 'OSTRA = oyster shell (Greek). Ancient Greeks voted to exile people using shells.' },
  { word: 'Pragmatic', pos: 'adjective', def: 'Dealing with things sensibly and realistically rather than theoretically.', example: 'A pragmatic approach to budgeting will serve you better than idealism.', tip: 'PRAG-matic. Pragmatic thinkers are PRACTICAL, not dreamy.' },
  { word: 'Quintessential', pos: 'adjective', def: 'Representing the most perfect or typical example of a quality or class.', example: 'Tea and scones are quintessential British afternoon treats.', tip: '"Quint" = fifth (Latin). Aristotle\'s "fifth essence" was the purest substance.' },
  { word: 'Reticent', pos: 'adjective', def: 'Not revealing one\'s thoughts or feelings readily.', example: 'She was reticent about sharing personal details at work.', tip: 'Reticent = RE-TIC-ent. Someone who keeps TICKING away inside, silently.' },
  { word: 'Sagacious', pos: 'adjective', def: 'Having or showing keen mental discernment and good judgment; wise.', example: 'The sagacious elder gave advice that proved correct years later.', tip: 'SAGE = wise herb. A sagacious person is like a sage — wise and seasoned.' },
  { word: 'Taciturn', pos: 'adjective', def: 'Reserved or uncommunicative in speech; saying little.', example: 'The taciturn detective revealed little during the press conference.', tip: 'TACIT = silent. A taciturn person stays SILENT and reserved.' },
  { word: 'Ubiquitous', pos: 'adjective', def: 'Present, appearing, or found everywhere.', example: 'Coffee shops have become ubiquitous in every city worldwide.', tip: 'Everywhere you go, you-be-quit-us of other options!' },
  { word: 'Verbose', pos: 'adjective', def: 'Using or expressed in more words than are needed.', example: 'His verbose explanation took ten minutes when two would have sufficed.', tip: 'VERB-ose. Full of verbs... and more verbs... and yet more verbs.' },
  { word: 'Whimsical', pos: 'adjective', def: 'Playfully quaint or fanciful, especially in an appealing and amusing way.', example: 'The café had whimsical decor with clocks on the ceiling and teacups on the walls.', tip: 'WHIM + sical. Full of whims — spontaneous, playful ideas.' },
  { word: 'Xenial', pos: 'adjective', def: 'Of or relating to hospitality toward guests or strangers.', example: 'The xenial innkeeper prepared a warm meal for every traveler.', tip: 'XENIA = hospitality (Greek). Xenial people are generous hosts.' },
  { word: 'Yearn', pos: 'verb', def: 'To have an intense feeling of longing for something.', example: 'She yearned to return to the mountains where she grew up.', tip: 'YEARN = EARN for something deeply. You earnestly want it.' },
  { word: 'Zealous', pos: 'adjective', def: 'Having or showing great energy or enthusiasm in pursuit of a cause.', example: 'The zealous volunteers worked through the night to prepare the event.', tip: 'ZEAL-ous. Full of ZEAL — burning passion and energy.' },
  { word: 'Articulate', pos: 'verb/adj', def: 'Express (an idea or feeling) fluently and coherently.', example: 'She was able to articulate her concerns in a calm, clear manner.', tip: 'ART-iculate. Making communication an ART form.' },
  { word: 'Benevolent', pos: 'adjective', def: 'Well meaning and kindly.', example: 'The benevolent donor funded scholarships for hundreds of students.', tip: 'BENE = good (Latin). A benevolent person does GOOD for others.' },
  { word: 'Cacophony', pos: 'noun', def: 'A harsh, discordant mixture of sounds.', example: 'The construction site created a cacophony that made concentration impossible.', tip: 'CACO = bad, PHON = sound. A BADLY sounding noise.' },
  { word: 'Dexterous', pos: 'adjective', def: 'Showing or having skill, especially with the hands.', example: 'The dexterous surgeon performed the delicate procedure without a tremor.', tip: 'DEXTER = right (Latin). Right-handed people were once thought most skilled.' },
  { word: 'Effervescent', pos: 'adjective', def: 'Vivacious and enthusiastic; (of a liquid) giving off bubbles.', example: 'Her effervescent personality lit up every room she entered.', tip: 'EFFER-vescent. Like bubbles efferVESCING — alive, bubbly, energetic.' },
  { word: 'Fervent', pos: 'adjective', def: 'Having or displaying a passionate intensity.', example: 'She was a fervent advocate for environmental protection.', tip: 'FERV = boil (Latin). Fervent feelings are HOT and boiling over.' },
  { word: 'Garrulous', pos: 'adjective', def: 'Excessively talkative, especially on trivial matters.', example: 'The garrulous neighbor always stopped by for a three-hour chat.', tip: 'GARR = chatter. A garrulous person chatters away endlessly.' },
  { word: 'Hapless', pos: 'adjective', def: 'Unfortunate.', example: 'The hapless traveler missed three connections and lost his luggage.', tip: 'HAP = luck (old English). Hapless = without any luck.' },
  { word: 'Idiosyncratic', pos: 'adjective', def: 'Relating to idiosyncrasy; peculiar or individual.', example: 'Her idiosyncratic style of teaching made every lesson memorable.', tip: 'IDIO = one\'s own (Greek). Your own unique, personal quirks.' },
  { word: 'Jaded', pos: 'adjective', def: 'Tired, bored, or lacking enthusiasm after having too much of something.', example: 'After years of travel, he had grown jaded and longed for home.', tip: 'Like a JADE stone — once precious, now so common it feels dull.' },
  { word: 'Kaleidoscope', pos: 'noun', def: 'A constantly changing pattern or sequence of elements.', example: 'The festival was a kaleidoscope of color, music, and culture.', tip: 'KALOS = beautiful, EIDOS = form. Beautiful, shifting forms.' },
  { word: 'Lament', pos: 'verb/noun', def: 'To express grief, regret, or sorrow; a passionate expression of sorrow.', example: 'She lamented the loss of the old library that once stood downtown.', tip: 'LA-ment. In music, lamentos are mournful, slow, sorrowful pieces.' },
  { word: 'Meticulous', pos: 'adjective', def: 'Showing great attention to detail or being very careful and precise.', example: 'Her meticulous planning ensured the project ran without a single hiccup.', tip: 'METU = fear (Latin). Originally meant being fearful of mistakes — now means careful.' },
  { word: 'Nostalgic', pos: 'adjective', def: 'Experiencing a wistful affection for the past.', example: 'Old photographs always make me feel nostalgic for childhood summers.', tip: 'NOSTOS = homecoming (Greek). Nostalgia is a longing to go home in time.' },
  { word: 'Oblivious', pos: 'adjective', def: 'Not aware of or not concerned about what is happening around one.', example: 'He was so absorbed in his book he was oblivious to the storm outside.', tip: 'OBLIVIOUS = OBLIV-ious. Like being in oblivion — total unawareness.' },
  { word: 'Peculiar', pos: 'adjective', def: 'Strange or odd; unusual.', example: 'There was a peculiar smell coming from the old bookshop.', tip: 'PECUL = cattle (Latin). Something peculiar to you = YOUR own cattle, unique possession.' },
  { word: 'Querulous', pos: 'adjective', def: 'Complaining in a petulant or whining manner.', example: 'The querulous customer complained about everything on the menu.', tip: 'QUER = complain. Querulous people always have a complaint queued up.' },
  { word: 'Raucous', pos: 'adjective', def: 'Making or constituting a disturbingly harsh and loud noise.', example: 'The raucous celebration went on until three in the morning.', tip: 'RAUC = hoarse (Latin). Raucous = rough, hoarse, noisy.' },
  { word: 'Stoic', pos: 'adjective', def: 'Enduring pain or hardship without showing feelings or complaining.', example: 'She faced the diagnosis with stoic calm, focusing on treatment options.', tip: 'STOIC = from the Greek porch (Stoa) where Stoic philosophers taught endurance.' },
  { word: 'Tenacious', pos: 'adjective', def: 'Tending to keep a firm hold of something; persistent.', example: 'His tenacious spirit kept him pushing forward despite every obstacle.', tip: 'TEN = hold (Latin). A tenacious person HOLDS ON tightly.' },
  { word: 'Unprecedented', pos: 'adjective', def: 'Never done or known before.', example: 'The company achieved unprecedented growth in its first year.', tip: '"Un-PRECED-ented" — nothing came BEFORE it. No precedent exists.' },
  { word: 'Vivacious', pos: 'adjective', def: 'Attractively lively and animated.', example: 'Her vivacious personality made her a natural leader.', tip: 'VIVA = live! Vivacious people are ALIVE with energy.' },
  { word: 'Wary', pos: 'adjective', def: 'Feeling or showing caution about possible dangers or problems.', example: 'She was wary of signing any contract without reading the fine print.', tip: 'WARE = aware (Old English). Wary people are on AWARE-ness alert.' },
  { word: 'Exuberant', pos: 'adjective', def: 'Filled with or characterized by a lively energy and excitement.', example: 'The crowd gave an exuberant cheer when the winning goal was scored.', tip: 'EX = out, UBER = over, abundant. Bursting over with energy!' },
  { word: 'Forlorn', pos: 'adjective', def: 'Pitifully sad and abandoned or lonely.', example: 'The forlorn puppy waited by the gate for its owner to return.', tip: 'FOR-lorn. Something that has been FOR-gotten and left ALONE.' },
  { word: 'Glib', pos: 'adjective', def: 'Fluent but insincere and shallow.', example: 'The politician gave a glib answer that satisfied no one.', tip: 'GLIB = slippery (Low German). Glib words slide right off without meaning.' },
  { word: 'Hapless', pos: 'adjective', def: 'Unfortunate; luckless.', example: 'The hapless contestant answered every question wrong.', tip: 'HAP = luck. HAP-less = luck-less. No luck at all.' },
  { word: 'Inquisitive', pos: 'adjective', def: 'Curious or inquiring.', example: 'Inquisitive students always ask the questions others are afraid to ask.', tip: 'IN-QUIS = seek (Latin). Inquisitive people are always SEEKING answers.' },
  { word: 'Jubilant', pos: 'adjective', def: 'Feeling or expressing great happiness and triumph.', example: 'The team was jubilant after winning the championship by a single point.', tip: 'JUBILEE = joyful celebration. Jubilant is pure, triumphant joy.' },
  { word: 'Kindle', pos: 'verb', def: 'To light or set on fire; to arouse or inspire a feeling.', example: 'The teacher kindled a love of reading in every student she taught.', tip: 'KINDLE = light a fire. You kindle interest just like lighting a flame.' },
  { word: 'Languid', pos: 'adjective', def: 'Weak or faint from illness or fatigue; slow and relaxed.', example: 'The summer heat made everyone feel languid and unmotivated.', tip: 'LANG = long (Germanic). Languid days stretch out L-O-N-G and slow.' },
  { word: 'Mundane', pos: 'adjective', def: 'Lacking interest or excitement; dull.', example: 'Even mundane tasks feel important when done with full attention.', tip: 'MUNDI = world (Latin). Mundane = worldly, ordinary, everyday stuff.' },
  { word: 'Nuance', pos: 'noun', def: 'A subtle difference in or shade of meaning, expression, or sound.', example: 'Understanding nuance is what separates intermediate from advanced speakers.', tip: 'NUA = cloud (French). Nuances are like light clouds — subtle shifts in color.' },
  { word: 'Obscure', pos: 'adjective', def: 'Not discovered or known about; not clearly expressed or easily understood.', example: 'He had an obscure hobby of collecting vintage matchboxes.', tip: 'OB-SCURE. Something hidden in the DARK, hard to see clearly.' },
  { word: 'Paramount', pos: 'adjective', def: 'More important than anything else; supreme.', example: 'Safety is paramount when working with electricity.', tip: 'PARA = above, MOUNT = mountain. Above the highest mountain = most important.' },
  { word: 'Quaint', pos: 'adjective', def: 'Attractively unusual or old-fashioned.', example: 'They stayed at a quaint bed-and-breakfast in the countryside.', tip: 'QUAINT sounds like "cute + ancient" — charmingly old-fashioned.' },
  { word: 'Resilience', pos: 'noun', def: 'The capacity to recover quickly from difficulties; toughness.', example: 'Building resilience is one of the most valuable skills you can develop.', tip: 'Like a rubber ball — resilience means BOUNCING BACK from impact.' },
  { word: 'Shrewd', pos: 'adjective', def: 'Having or showing sharp powers of judgment; astute.', example: 'A shrewd investor knows when to hold on and when to sell.', tip: 'SHREW = sharp-snouted animal. Shrewd people have a sharp, pointed mind.' },
  { word: 'Tangible', pos: 'adjective', def: 'Perceptible by touch; clear and definite; real.', example: 'After months of work, we finally had tangible results to show.', tip: 'TANG = touch (Latin). Tangible = something you can TOUCH and hold.' },
  { word: 'Undulate', pos: 'verb', def: 'To move with a smooth wavelike motion.', example: 'Fields of wheat undulate beautifully in the gentle breeze.', tip: 'UNDUL = wave (Latin). Think of ocean UNDULATIONS — rolling waves.' },
  { word: 'Vindicate', pos: 'verb', def: 'To clear someone of blame or suspicion.', example: 'New evidence emerged to fully vindicate the wrongly accused man.', tip: 'VIN-dicate. Victory + indicate. Indicating your VINdicated innocence.' },
  { word: 'Wistful', pos: 'adjective', def: 'Having or showing a feeling of vague or regretful longing.', example: 'She gave a wistful smile when she passed her old school.', tip: 'WISTFUL = wishful but tinged with sadness. "I wish..." + a sigh.' },
  { word: 'Exacerbate', pos: 'verb', def: 'To make a problem, bad situation, or negative feeling worse.', example: 'Lack of sleep will exacerbate feelings of anxiety.', tip: 'EX-ACER = to sharpen (Latin). Making the sharp edge even sharper = worse.' },
  { word: 'Fastidious', pos: 'adjective', def: 'Very attentive to accuracy and detail; very concerned about cleanliness.', example: 'She was fastidious about keeping her workspace organized.', tip: 'FASTI = proud (Latin). A fastidious person has pride in every precise detail.' },
  { word: 'Grandeur', pos: 'noun', def: 'Splendor and impressiveness, especially of appearance or style.', example: 'The grandeur of the ancient cathedral left visitors speechless.', tip: 'GRAND-eur. Grand + the French suffix = supreme GRANDNESS.' },
  { word: 'Harbinger', pos: 'noun', def: 'A person or thing that announces or signals the approach of another.', example: 'The first robin of spring is a harbinger of warmer days to come.', tip: 'HARBOR + -inger. Someone who prepares the HARBOR (shelter) in advance.' },
  { word: 'Impeccable', pos: 'adjective', def: 'In accordance with the highest standards; faultless.', example: 'Her impeccable grammar impressed even native English speakers.', tip: 'IM-PECC = no sin (Latin). Impeccable = without any fault or sin.' },
  { word: 'Jocular', pos: 'adjective', def: 'Fond of or characterized by joking; humorous.', example: 'His jocular manner made even difficult meetings more bearable.', tip: 'JOCUL = joke (Latin). Full of jokes = jocular.' },
  { word: 'Keen', pos: 'adjective', def: 'Eager; enthusiastic; sharp or penetrating.', example: 'She had a keen eye for detail that made her an excellent editor.', tip: 'KEEN = sharp (Old English). A keen mind cuts through to the truth.' },
  { word: 'Lucid', pos: 'adjective', def: 'Expressed clearly; easy to understand.', example: 'His lucid explanation of quantum physics amazed the students.', tip: 'LUCID = light (Latin). Lucid explanations ILLUMINATE the topic.' },
  { word: 'Mollify', pos: 'verb', def: 'To appease the anger or anxiety of someone.', example: 'She mollified the upset customer with a sincere apology.', tip: 'MOLLI = soft (Latin). You SOFTEN someone\'s anger when you mollify them.' },
  { word: 'Nefarious', pos: 'adjective', def: 'Wicked or criminal.', example: 'The villain\'s nefarious plan was thwarted at the last moment.', tip: 'NE = not, FAS = divine law (Latin). Nefarious = against divine law = very bad.' },
  { word: 'Opulent', pos: 'adjective', def: 'Ostentatiously rich and luxurious or lavish.', example: 'The opulent ballroom was decorated with gold leaf and crystal chandeliers.', tip: 'OPE = wealth (Latin). Opulent = overflowing with wealth and luxury.' },
  { word: 'Pensive', pos: 'adjective', def: 'Engaged in, involving, or reflecting deep or serious thought.', example: 'She sat in a pensive mood, staring at the horizon for hours.', tip: 'PENS = weigh (Latin). Pensive = weighing thoughts carefully in your mind.' },
  { word: 'Querulous', pos: 'adjective', def: 'Complaining in a petulant or whining manner.', example: 'The querulous child complained throughout the entire car journey.', tip: 'QUER = complain (Latin). Always QUEUED up with complaints.' },
  { word: 'Ramify', pos: 'verb', def: 'To spread or branch out.', example: 'The consequences of that one decision ramified in unexpected ways.', tip: 'RAMI = branch (Latin). Like tree branches spreading in all directions.' },
  { word: 'Scrupulous', pos: 'adjective', def: 'Diligent, thorough, and extremely attentive to details.', example: 'A scrupulous accountant double-checks every figure.', tip: 'SCRUPL = small stone (Latin). Careful of even the smallest pebble in your way.' },
  { word: 'Tenuous', pos: 'adjective', def: 'Very weak or slight.', example: 'Her argument was built on tenuous assumptions that didn\'t hold up.', tip: 'TEN = thin (Latin). Tenuous = stretched so thin it might snap.' },
  { word: 'Unfurl', pos: 'verb', def: 'To make or become spread out from a rolled or folded state.', example: 'The flags unfurled in the morning breeze for the ceremony.', tip: 'UN + FURL. Un-roll, un-fold, un-wrap. Like opening a scroll.' },
  { word: 'Vacillate', pos: 'verb', def: 'To waver between different opinions or actions; to be indecisive.', example: 'He vacillated between two job offers for weeks before deciding.', tip: 'VACIL = to sway (Latin). Like a pendulum swinging back and forth.' },
  { word: 'Wane', pos: 'verb', def: 'To decrease in vigor, power, or extent; to become weaker.', example: 'As autumn approached, the enthusiasm for the project began to wane.', tip: 'WANE = opposite of wax. Moon WANES when it gets smaller.' },
  { word: 'Exorbitant', pos: 'adjective', def: 'Unreasonably high (of a price or amount charged).', example: 'The hotel charged an exorbitant fee for parking.', tip: 'EX-ORBIT = outside the orbit. An exorbitant price flies way out of range.' },
  { word: 'Fervor', pos: 'noun', def: 'Intense and passionate feeling.', example: 'She tackled the project with a fervor that inspired the whole team.', tip: 'FERV = to boil (Latin). Fervor is boiling-hot passion.' },
  { word: 'Glean', pos: 'verb', def: 'Extract information from various sources.', example: 'From the lecture, students could glean several practical tips.', tip: 'GLEAN = gather grain. You pick up knowledge bit by bit, like harvesting.' },
  { word: 'Hackneyed', pos: 'adjective', def: 'Lacking significance through having been overused; unoriginal.', example: 'The speech was full of hackneyed phrases that put the audience to sleep.', tip: 'HACKNEY = horse for hire (old). Overused, tired like a worn-out old horse.' },
  { word: 'Imminent', pos: 'adjective', def: 'About to happen.', example: 'With dark clouds gathering, rain seemed imminent.', tip: 'IM-MINENT = hanging over (Latin). Like a storm cloud hanging right above you.' },
  { word: 'Judicious', pos: 'adjective', def: 'Having, showing, or done with good judgment or sense.', example: 'A judicious use of resources can make the budget stretch much further.', tip: 'JUDIC = judge (Latin). A judicious person judges situations wisely.' },
  { word: 'Kinship', pos: 'noun', def: 'A sharing of characteristics or origins; a feeling of being close to someone.', example: 'Despite different cultures, they felt an instant kinship over their shared love of music.', tip: 'KIN = family. Kinship is that feeling of family even with strangers.' },
  { word: 'Listless', pos: 'adjective', def: 'Lacking energy or enthusiasm.', example: 'She felt listless and unmotivated after the long winter.', tip: 'LIST-less = no desire to DO anything. Your to-do list is empty because you don\'t care.' },
  { word: 'Meander', pos: 'verb', def: 'To follow a winding course; to wander without purpose.', example: 'We spent the afternoon meandering through the old town\'s narrow streets.', tip: 'MEANDER = from the Maeander River in Turkey, famous for its winding path.' },
  { word: 'Nascent', pos: 'adjective', def: 'Just coming into existence and beginning to display signs of future potential.', example: 'The nascent technology shows great promise for the medical field.', tip: 'NASC = to be born (Latin). Nascent = just being born, brand new.' },
  { word: 'Ominous', pos: 'adjective', def: 'Giving the impression that something bad or unpleasant is going to happen.', example: 'The dark, ominous clouds signaled a powerful storm approaching.', tip: 'OMIN = omen (Latin). Ominous = full of bad omens.' }
];
